### ISSUE TITLE
`IndexError` on Actor Analysis

### ISSUE THREAD

**Issue by f-hafner** [navigating-stories/orange-story-navigator#37]
##### Story Navigator version
0.0.18 (commit 8732988)

##### Orange version
3.36.2

##### Expected behavior
Can run actor analysis without error.

##### Actual behavior
get the following error
```bash

Exception:
IndexError: index 38 is out of bounds for axis 0 with size 38
Module:
Orange.data.table:96
Widget Name:
Actors
Widget Module:
storynavigation.widgets.OWSNActorAnalysis:591
Widget Scheme:
<?xml version='1.0' encoding='utf-8'?> <scheme version="2.0" title="" description=""> <nodes> <node id="0" name="Import Documents" qualified_name="orangecontrib.text.widgets.owimportdocuments.OWImportDocuments" project_name="Orange3-Text" version="" title="Import Documents" position="(188.0, 253.0)" /> <node id="1" name="File" qualified_name="Orange.widgets.data.owfile.OWFile" project_name="Orange3" version="" title="File" position="(162.0, 603.0)" /> <node id="2" name="Elements" qualified_name="storynavigation.widgets.OWSNTagger.OWSNTagger" project_name="storynavigator" version="" title="Elements" position="(337.0, 599.0)" /> <node id="3" name="Data Table" qualified_name="Orange.widgets.data.owtable.OWTable" project_name="Orange3" version="" title="Data Table" position="(555.0, 611.0)" /> <node id="4" name="Actors" qualified_name="storynavigation.widgets.OWSNActorAnalysis.OWSNActorAnalysis" project_name="storynavigator" version="" title="Actors" position="(858.0, 217.0)" /> <node id="5" name="Data Table" qualified_name="Orange.widgets.data.owtable.OWTable" project_name="Orange3" version="" title="Data Table (1)" position="(979.0, 127.0)" /> <node id="6" name="Actions" qualified_name="storynavigation.widgets.OWSNActionAnalysis.OWSNActionAnalysis" project_name="storynavigator" version="" title="Actions" position="(850.0, 617.0)" /> <node id="7" name="Select Rows" qualified_name="Orange.widgets.data.owselectrows.OWSelectRows" project_name="Orange3" version="" title="Select Rows" position="(1151.0, 130.0)" /> <node id="8" name="Bar Plot" qualified_name="Orange.widgets.visualize.owbarplot.OWBarPlot" project_name="Orange3" version="" title="Bar Plot" position="(1276.0, 136.0)" /> <node id="9" name="Data Table" qualified_name="Orange.widgets.data.owtable.OWTable" project_name="Orange3" version="" title="Data Table (2)" position="(1079.0, 447.0)" /> </nodes> <links> <link id="0" source_node_id="0" sink_node_id="2" source_channel="Corpus" sink_channel="Stories" enabled="true" source_channel_id="data" sink_channel_id="stories" /> <link id="1" source_node_id="1" sink_node_id="2" source_channel="Data" sink_channel="Custom tags" enabled="true" source_channel_id="data" sink_channel_id="custom_tag_dict" /> <link id="2" source_node_id="2" sink_node_id="3" source_channel="Story elements" sink_channel="Data" enabled="true" source_channel_id="dataset_level_data" sink_channel_id="data" /> <link id="3" source_node_id="3" sink_node_id="4" source_channel="Data" sink_channel="Story elements" enabled="true" source_channel_id="annotated_data" sink_channel_id="story_elements" /> <link id="4" source_node_id="4" sink_node_id="5" source_channel="Actor stats: all" sink_channel="Data" enabled="true" source_channel_id="story_collection_results" sink_channel_id="data" /> <link id="5" source_node_id="3" sink_node_id="6" source_channel="Data" sink_channel="Story elements" enabled="true" source_channel_id="annotated_data" sink_channel_id="story_elements" /> <link id="6" source_node_id="0" sink_node_id="4" source_channel="Corpus" sink_channel="Stories" enabled="true" source_channel_id="data" sink_channel_id="stories" /> <link id="7" source_node_id="0" sink_node_id="6" source_channel="Corpus" sink_channel="Stories" enabled="true" source_channel_id="data" sink_channel_id="stories" /> <link id="8" source_node_id="5" sink_node_id="7" source_channel="Selected Data" sink_channel="Data" enabled="true" source_channel_id="selected_data" sink_channel_id="data" /> <link id="9" source_node_id="7" sink_node_id="8" source_channel="Matching Data" sink_channel="Data" enabled="true" source_channel_id="matching_data" sink_channel_id="data" /> <link id="10" source_node_id="6" sink_node_id="9" source_channel="Action table: all" sink_channel="Data" enabled="true" source_channel_id="actor_action_table_full" sink_channel_id="data" /> </links> <annotations /> <thumbnail /> <node_properties> <properties node_id="0" format="pickle">gASVYQMAAAAAAAB9lCiMEmNvbnRyb2xBcmVhVmlzaWJsZZSIjAtjdXJyZW50UGF0aJSMUC9ob21l L2ZsYXZpby9yZXBvc2l0b3JpZXMvcHJvamVjdHMvbmF2aWdhdGluZy1zdG9yaWVzL2RhdGEvc3Vi c2V0LWNvcm9uYS1kYXRhc2V0lIwIbGVtbWFfY2KUiIwGbmVyX2NilImMBnBvc19jYpSJjAxyZWNl bnRfcGF0aHOUXZQojB5vcmFuZ2V3aWRnZXQudXRpbHMuZmlsZWRpYWxvZ3OUjApSZWNlbnRQYXRo lJOUKYGUfZQojAdhYnNwYXRolGgDjAZwcmVmaXiUTowHcmVscGF0aJROjAV0aXRsZZSMAJSMBXNo ZWV0lGgSjAtmaWxlX2Zvcm1hdJROdWJoCymBlH2UKGgOjE4vaG9tZS9mbGF2aW8vcmVwb3NpdG9y aWVzL3Byb2plY3RzL25hdmlnYXRpbmctc3Rvcmllcy9kYXRhL2Z1bGwtY29yb25hLWRhdGFzZXSU aA9OaBBOaBFoEmgTaBJoFE51YmgLKYGUfZQoaA6MFS9ob21lL2ZsYXZpby9kYXRhc2V0c5RoD05o EE5oEWgSaBNoEmgUTnViZYwLcmVjZW50X3VybHOUXZSME3NhdmVkV2lkZ2V0R2VvbWV0cnmUQ0IB 2dDLAAMAAAAABawAAAHSAAAHfAAAA0MAAAWsAAAB9wAAB3wAAANDAAAAAAAAAAANcAAABawAAAH3 AAAHfAAAA0OUjAZzb3VyY2WUSwCMC19fdmVyc2lvbl9flEsBjBBjb250ZXh0X3NldHRpbmdzlF2U KIwVb3Jhbmdld2lkZ2V0LnNldHRpbmdzlIwHQ29udGV4dJSTlCmBlH2UKIwGdmFsdWVzlH2UKIwI bGFuZ3VhZ2WUjAVEdXRjaJRoIEsBdYwOZG9jdW1lbnRzX2hhc2iUigjJ4YiyaFNLU3ViaCUpgZR9 lChoKH2UKIwIbGFuZ3VhZ2WUjAVEdXRjaJRoIEsBdWgsigj09QtBA2J2uHViaCUpgZR9lChoKH2U KIwIbGFuZ3VhZ2WUjAVEdXRjaJRoIEsBdWgsigjdt6Ew5rEE3nViaCUpgZR9lChoKH2UKGg1aDZo IEsBdWgsigiXl/7HI4Q7ZHViZXUu </properties> <properties node_id="1" format="pickle">gASVDwsAAAAAAAB9lCiMEmNvbnRyb2xBcmVhVmlzaWJsZZSIjAxyZWNlbnRfcGF0aHOUXZQojB5v cmFuZ2V3aWRnZXQudXRpbHMuZmlsZWRpYWxvZ3OUjApSZWNlbnRQYXRolJOUKYGUfZQojAdhYnNw YXRolIyTL2hvbWUvZmxhdmlvL3JlcG9zaXRvcmllcy9wcm9qZWN0cy9uYXZpZ2F0aW5nLXN0b3Jp ZXMvb3JhbmdlLXN0b3J5LW5hdmlnYXRvci9vcmFuZ2Vjb250cmliL3N0b3J5bmF2aWdhdGlvbi9y ZXNvdXJjZXMvZHV0Y2hfaGFsbGlkYXlfYWN0aW9uX2xpc3QuY3N2lIwGcHJlZml4lE6MB3JlbHBh dGiUTowFdGl0bGWUjACUjAVzaGVldJRoDowLZmlsZV9mb3JtYXSUTnViaAYpgZR9lChoCYyHL2hv bWUvZmxhdmlvL3JlcG9zaXRvcmllcy9wcm9qZWN0cy9uYXZpZ2F0aW5nLXN0b3JpZXMvb3Jhbmdl LXN0b3J5LW5hdmlnYXRvci8udmVudi9saWIvcHl0aG9uMy45L3NpdGUtcGFja2FnZXMvT3Jhbmdl L2RhdGFzZXRzL2lyaXMudGFilGgLjA9zYW1wbGUtZGF0YXNldHOUaAyMCGlyaXMudGFilGgNaA5o D2gOaBBOdWJoBimBlH2UKGgJjIovaG9tZS9mbGF2aW8vcmVwb3NpdG9yaWVzL3Byb2plY3RzL25h dmlnYXRpbmctc3Rvcmllcy9vcmFuZ2Utc3RvcnktbmF2aWdhdG9yLy52ZW52L2xpYi9weXRob24z Ljkvc2l0ZS1wYWNrYWdlcy9PcmFuZ2UvZGF0YXNldHMvdGl0YW5pYy50YWKUaAtoFGgMjAt0aXRh bmljLnRhYpRoDWgOaA9oDmgQTnViaAYpgZR9lChoCYyKL2hvbWUvZmxhdmlvL3JlcG9zaXRvcmll cy9wcm9qZWN0cy9uYXZpZ2F0aW5nLXN0b3JpZXMvb3JhbmdlLXN0b3J5LW5hdmlnYXRvci8udmVu di9saWIvcHl0aG9uMy45L3NpdGUtcGFja2FnZXMvT3JhbmdlL2RhdGFzZXRzL2hvdXNpbmcudGFi lGgLaBRoDIwLaG91c2luZy50YWKUaA1oDmgPaA5oEE51YmgGKYGUfZQoaAmMkC9ob21lL2ZsYXZp by9yZXBvc2l0b3JpZXMvcHJvamVjdHMvbmF2aWdhdGluZy1zdG9yaWVzL29yYW5nZS1zdG9yeS1u YXZpZ2F0b3IvLnZlbnYvbGliL3B5dGhvbjMuOS9zaXRlLXBhY2thZ2VzL09yYW5nZS9kYXRhc2V0 cy9oZWFydF9kaXNlYXNlLnRhYpRoC2gUaAyMEWhlYXJ0X2Rpc2Vhc2UudGFilGgNaA5oD2gOaBBO dWJoBimBlH2UKGgJjJEvaG9tZS9mbGF2aW8vcmVwb3NpdG9yaWVzL3Byb2plY3RzL25hdmlnYXRp bmctc3Rvcmllcy9vcmFuZ2Utc3RvcnktbmF2aWdhdG9yLy52ZW52L2xpYi9weXRob24zLjkvc2l0 ZS1wYWNrYWdlcy9PcmFuZ2UvZGF0YXNldHMvYnJvd24tc2VsZWN0ZWQudGFilGgLaBRoDIwSYnJv d24tc2VsZWN0ZWQudGFilGgNaA5oD2gOaBBOdWJoBimBlH2UKGgJjIYvaG9tZS9mbGF2aW8vcmVw b3NpdG9yaWVzL3Byb2plY3RzL25hdmlnYXRpbmctc3Rvcmllcy9vcmFuZ2Utc3RvcnktbmF2aWdh dG9yLy52ZW52L2xpYi9weXRob24zLjkvc2l0ZS1wYWNrYWdlcy9PcmFuZ2UvZGF0YXNldHMvem9v LnRhYpRoC2gUaAyMB3pvby50YWKUaA1oDmgPaA5oEE51YmWMC3JlY2VudF91cmxzlF2UjBNzYXZl ZFdpZGdldEdlb21ldHJ5lENCAdnQywADAAAAAAONAAACCwAABeQAAASsAAADjQAAAjAAAAXkAAAE rAAAAAAAAAAADXAAAAONAAACMAAABeQAAASslIwLc2hlZXRfbmFtZXOUfZSMBnNvdXJjZZRLAIwD dXJslGgOjA1kb21haW5fZWRpdG9ylH2UjAtfX3ZlcnNpb25fX5RLAYwQY29udGV4dF9zZXR0aW5n c5RdlIwVb3Jhbmdld2lkZ2V0LnNldHRpbmdzlIwHQ29udGV4dJSTlCmBlH2UKIwGdmFsdWVzlH2U KIwJdmFyaWFibGVzlF2UaDJ9lGg+XZQoXZQojAVyZWFsbZSMFE9yYW5nZS5kYXRhLnZhcmlhYmxl lIwOU3RyaW5nVmFyaWFibGWUk5RLAowVQmVpbmcsIERvaW5nLCBTZW5zaW5nlIllXZQojAdwcm9j ZXNzlGhGSwKMPUJlaGF2aW9yYWwsIEV4aXN0ZW50aWFsLCBNYXRlcmlhbCwgTWVudGFsLCBSZWxh dGlvbmFsLCBWZXJiYWyUiWVdlCiMBnByb3N1YpRoRksCjIRCZWhhdmlvcmFsLCBFeGlzdGVudGlh bCwgTWF0ZXJpYWwsIE1lbnRhbDogQ29nbml0aXZlLCBNZW50YWw6IERlc2lkZXJhdGl2ZSwgTWVu dGFsOiBFbW90aXZlLCBNZW50YWw6IFBlcnNwZWN0aXZlLCBSZWxhdGlvbmFsLCBWZXJiYWyUiWVd lCiMA3N1YpRoRksCjLNBY3RzIHZlcmJhbGx5LCBCb2RpbHkgcG9zdHVyZXMsIENpcmN1bXN0YW50 aWFsLCBDb2duaXRpdmUsIENyZWF0aXZlLCBEZXNpZGVyYXRpdmUsIERpc3Bvc2l0aXZlLCBFbW90 aXZlLCBFeGlzdGVudGlhbCwgSW50ZW5zaXZlLCBQZXJzcGVjdGl2ZSwgUGh5c2lvbG9naWNhbCwg UG9zc2Vzc2l2ZSwgVmVyYmFsIGFjdJSJZV2UKIwEd29yZJRoRksCaA6JZWVzaDRLAXWMCmF0dHJp YnV0ZXOUKIwFcmVhbG2UXZQojAVCZWluZ5SMBURvaW5nlIwHU2Vuc2luZ5RlhpSMB3Byb2Nlc3OU XZQojApCZWhhdmlvcmFslIwLRXhpc3RlbnRpYWyUjAhNYXRlcmlhbJSMBk1lbnRhbJSMClJlbGF0 aW9uYWyUjAZWZXJiYWyUZYaUjAZwcm9zdWKUXZQojApCZWhhdmlvcmFslIwLRXhpc3RlbnRpYWyU jAhNYXRlcmlhbJSMEU1lbnRhbDogQ29nbml0aXZllIwUTWVudGFsOiBEZXNpZGVyYXRpdmWUjA9N ZW50YWw6IEVtb3RpdmWUjBNNZW50YWw6IFBlcnNwZWN0aXZllIwKUmVsYXRpb25hbJSMBlZlcmJh bJRlhpSMA3N1YpRdlCiMDUFjdHMgdmVyYmFsbHmUjA9Cb2RpbHkgcG9zdHVyZXOUjA5DaXJjdW1z dGFudGlhbJSMCUNvZ25pdGl2ZZSMCENyZWF0aXZllIwMRGVzaWRlcmF0aXZllIwLRGlzcG9zaXRp dmWUjAdFbW90aXZllIwLRXhpc3RlbnRpYWyUjAlJbnRlbnNpdmWUjAtQZXJzcGVjdGl2ZZSMDVBo eXNpb2xvZ2ljYWyUjApQb3NzZXNzaXZllIwKVmVyYmFsIGFjdJRlhpR0lIwFbWV0YXOUjAR3b3Jk lEsDhpSFlIwKY2xhc3NfdmFyc5QpjBJtb2RpZmllZF92YXJpYWJsZXOUXZR1YmF1Lg== </properties> <properties node_id="2" format="literal">{'autocommit': True, 'controlAreaVisible': True, 'savedWidgetGeometry': b'\x01\xd9\xd0\xcb\x00\x03\x00\x00\x00\x00\x02\xc0\x00\x00\x02f\x00\x00\x05?\x00\x00\x04j\x00\x00\x02\xc0\x00\x00\x02\x8b\x00\x00\x05?\x00\x00\x04j\x00\x00\x00\x00\x00\x00\x00\x00\rp\x00\x00\x02\xc0\x00\x00\x02\x8b\x00\x00\x05?\x00\x00\x04j', '__version__': 2, 'context_settings': []}</properties> <properties node_id="3" format="literal">{'auto_commit': True, 'color_by_class': True, 'controlAreaVisible': True, 'savedWidgetGeometry': b'\x01\xd9\xd0\xcb\x00\x03\x00\x00\x00\x00\x06\xdc\x00\x00\x00@\x00\x00\ro\x00\x00\x05\x9f\x00\x00\x06\xdc\x00\x00\x00@\x00\x00\ro\x00\x00\x05\x9f\x00\x00\x00\x00\x00\x00\x00\x00\rp\x00\x00\x06\xdc\x00\x00\x00@\x00\x00\ro\x00\x00\x05\x9f', 'select_rows': True, 'show_attribute_labels': True, 'show_distributions': False, 'stored_selection': {'rows': [], 'columns': []}, 'stored_sort': [], '__version__': 1}</properties> <properties node_id="4" format="pickle">gASVEwEAAAAAAAB9lCiMB2FsbF9wb3OUiYwKYXV0b2NvbW1pdJSIjBJjb250cm9sQXJlYVZpc2li bGWUiIwGY3VzdG9tlIiMBW5vdW5zlImME3NhdmVkV2lkZ2V0R2VvbWV0cnmUQ0IB2dDLAAMAAAAA BtwAAAAbAAANbwAABZ8AAAbcAAAAQAAADW8AAAWfAAAAAAAAAAANcAAABtwAAABAAAANbwAABZ+U jBJzZWxlY3RlZF9kb2N1bWVudHOUj5QoSwCQjAtzaG93X3Rva2Vuc5SJjAVzdWJqc5SJjAh0YWdf dHlwZZRLAYwIemVyb19wb3OUiYwLX192ZXJzaW9uX1+USwKMEGNvbnRleHRfc2V0dGluZ3OUXZR1 Lg== </properties> <properties node_id="5" format="literal">{'auto_commit': True, 'color_by_class': True, 'controlAreaVisible': True, 'savedWidgetGeometry': b'\x01\xd9\xd0\xcb\x00\x03\x00\x00\x00\x00\x03\xa7\x00\x00\x02i\x00\x00\x06&amp;\x00\x00\x04m\x00\x00\x03\xa7\x00\x00\x02\x8e\x00\x00\x06&amp;\x00\x00\x04m\x00\x00\x00\x00\x00\x00\x00\x00\rp\x00\x00\x03\xa7\x00\x00\x02\x8e\x00\x00\x06&amp;\x00\x00\x04m', 'select_rows': True, 'show_attribute_labels': True, 'show_distributions': False, 'stored_selection': {'rows': [], 'columns': []}, 'stored_sort': [], '__version__': 1}</properties> <properties node_id="6" format="pickle">gASVHAEAAAAAAAB9lCiMB2FsbF9wb3OUiYwKYXV0b2NvbW1pdJSJjBJjb250cm9sQXJlYVZpc2li bGWUiIwGY3VzdG9tlImMCHBhc3RfdmJ6lIiMC3ByZXNlbnRfdmJ6lIiME3NhdmVkV2lkZ2V0R2Vv bWV0cnmUQ0IB2dDLAAMAAAAAEiQAAACDAAAV/AAAAmgAABIkAAAAqAAAFfwAAAJoAAAAAQAAAAAH gAAAEiQAAACoAAAV/AAAAmiUjBJzZWxlY3RlZF9kb2N1bWVudHOUj5QoSwCQjAtzaG93X3Rva2Vu c5SJjAh0YWdfdHlwZZRLAYwIemVyb19wb3OUiYwLX192ZXJzaW9uX1+USwKMEGNvbnRleHRfc2V0 dGluZ3OUXZR1Lg== </properties> <properties node_id="7" format="pickle">gASVwgEAAAAAAAB9lCiMC2F1dG9fY29tbWl0lIiMEmNvbnRyb2xBcmVhVmlzaWJsZZSIjBBwdXJn ZV9hdHRyaWJ1dGVzlImMDXB1cmdlX2NsYXNzZXOUiYwTc2F2ZWRXaWRnZXRHZW9tZXRyeZRDQgHZ 0MsAAwAAAAAFpgAAAaMAAAf9AAADMgAABaYAAAGjAAAH/QAAAzIAAAAAAAAAAA1wAAAFpgAAAaMA AAf9AAADMpSMEHVwZGF0ZV9vbl9jaGFuZ2WUiIwLX192ZXJzaW9uX1+USwKMEGNvbnRleHRfc2V0 dGluZ3OUXZSMFW9yYW5nZXdpZGdldC5zZXR0aW5nc5SMB0NvbnRleHSUk5QpgZR9lCiMBnZhbHVl c5R9lCiMCmNvbmRpdGlvbnOUXZQojAdzdG9yeWlklEsBSwBdlIwEU1QxM5RhdJRhaAhLAnWMCmF0 dHJpYnV0ZXOUfZQoaBRLAYwKc2VnbWVudF9pZJRLAYwIcmF3X2ZyZXGUSwKMCXN1YmpfZnJlcZRL AowGYWdlbmN5lEsCjA1wcm9taW5lbmNlX3NmlEsCdYwFbWV0YXOUfZSMCmN1c3RvbV9zdWKUSwNz dWJhdS4= </properties> <properties node_id="8" format="pickle">gASV4gEAAAAAAAB9lCiMC2F1dG9fY29tbWl0lIiMEmNvbnRyb2xBcmVhVmlzaWJsZZSIjBNzYXZl ZFdpZGdldEdlb21ldHJ5lENCAdnQywADAAAAAAbCAAAAyAAADIUAAAQAAAAGwgAAAO0AAAyFAAAE AAAAAAAAAAAADXAAAAbCAAAA7QAADIUAAAQAlIwJc2VsZWN0aW9ulE6MD3Zpc3VhbF9zZXR0aW5n c5R9lIwFZ3JhcGiUfZSMC19fdmVyc2lvbl9flEsBjBBjb250ZXh0X3NldHRpbmdzlF2UjBVvcmFu Z2V3aWRnZXQuc2V0dGluZ3OUjAdDb250ZXh0lJOUKYGUfZQojAZ2YWx1ZXOUfZQojAlhbm5vdF92 YXKUTkr+////hpSMCWNvbG9yX3ZhcpSMCnNlZ21lbnRfaWSUS2WGlIwJZ3JvdXBfdmFylGgXS2WG lIwMc2VsZWN0ZWRfdmFylIwIcmF3X2ZyZXGUS2aGlGgIfZRoCksBdYwKYXR0cmlidXRlc5R9lCiM B3N0b3J5aWSUSwFoF0sBaBxLAowJc3Vial9mcmVxlEsCjAZhZ2VuY3mUSwKMDXByb21pbmVuY2Vf c2aUSwJ1jAVtZXRhc5R9lIwKY3VzdG9tX3N1YpRLA3N1YmF1Lg== </properties> <properties node_id="9" format="literal">{'auto_commit': True, 'color_by_class': True, 'controlAreaVisible': True, 'savedWidgetGeometry': b'\x01\xd9\xd0\xcb\x00\x03\x00\x00\x00\x00\x03\xa7\x00\x00\x02i\x00\x00\x06&amp;\x00\x00\x04m\x00\x00\x03\xa7\x00\x00\x02\x8e\x00\x00\x06&amp;\x00\x00\x04m\x00\x00\x00\x00\x00\x00\x00\x00\rp\x00\x00\x03\xa7\x00\x00\x02\x8e\x00\x00\x06&amp;\x00\x00\x04m', 'select_rows': True, 'show_attribute_labels': True, 'show_distributions': False, 'stored_selection': {'rows': [], 'columns': []}, 'stored_sort': [], '__version__': 1}</properties> </node_properties> <session_state> <window_groups /> </session_state> </scheme> 
Version:
3.36.2
Environment:
Python 3.9.13 on Linux 5.15.0-100-generic #110~20.04.1-Ubuntu SMP Tue Feb 13 14:25:03 UTC 2024 x86_64
Installed Packages:
AnyQt==0.2.0, Babel==2.14.0, Bottleneck==1.3.8, DHTMLParser3==3.0.17, Jinja2==3.1.3, MarkupSafe==2.1.5, Orange3-Network==1.9.0, Orange3-Text==1.15.0, Orange3==3.36.2, PyQt5-Qt5==5.15.2, PyQt5-sip==12.13.0, PyQt5==5.15.10, PyQt6-Qt6==6.6.2, PyQt6-sip==13.6.0, PyQt6==6.6.1, PyQtWebEngine-Qt5==5.15.2, PyQtWebEngine==5.15.6, PyYAML==6.0.1, QtPy==2.4.1, SecretStorage==3.3.3, XlsxWriter==3.2.0, alabaster==0.7.16, annotated-types==0.6.0, anyio==4.3.0, asttokens==2.4.1, attrs==23.2.0, baycomp==1.0.3, beautifulsoup4==4.12.3, biopython==1.83, blis==0.7.11, catalogue==2.0.10, catboost==1.2.3, cattrs==23.2.3, certifi==2024.2.2, cffi==1.16.0, chardet==5.2.0, charset-normalizer==3.3.2, click==8.1.7, cloudpathlib==0.16.0, comm==0.2.1, commonmark==0.9.1, confection==0.1.4, conllu==4.5.3, contourpy==1.2.0, coverage==7.4.3, cryptography==42.0.5, cycler==0.12.1, cymem==2.0.8, debugpy==1.8.1, decorator==5.1.1, defusedxml==0.7.1, dictdiffer==0.9.0, docutils==0.20.1, docx2txt==0.8, et-xmlfile==1.1.0, exceptiongroup==1.2.0, executing==2.0.1, filelock==3.13.1, fonttools==4.49.0, fsspec==2024.2.0, gensim==4.3.2, graphviz==0.20.1, h11==0.14.0, httpcore==1.0.4, httpx==0.27.0, huggingface-hub==0.21.3, idna==3.6, imagesize==1.4.1, importlib-metadata==7.0.1, importlib-resources==6.1.2, ipykernel==6.29.3, ipython==8.18.1, jaraco.classes==3.3.1, jedi==0.19.1, jeepney==0.8.0, jellyfish==1.0.3, joblib==1.3.2, jupyter-client==8.6.0, jupyter-core==5.7.1, keyring==24.3.1, keyrings.alt==5.0.0, kiwisolver==1.4.5, langcodes==3.3.0, langdetect==1.0.9, lemmagen3==3.5.1, matplotlib-inline==0.1.6, matplotlib==3.8.3, more-itertools==10.2.0, mpmath==1.3.0, murmurhash==1.0.10, nest-asyncio==1.6.0, networkx==3.2.1, nl-core-news-sm==3.7.0, nltk==3.8.1, numpy==1.26.4, nvidia-cublas-cu12==12.1.3.1, nvidia-cuda-cupti-cu12==12.1.105, nvidia-cuda-nvrtc-cu12==12.1.105, nvidia-cuda-runtime-cu12==12.1.105, nvidia-cudnn-cu12==8.9.2.26, nvidia-cufft-cu12==11.0.2.54, nvidia-curand-cu12==10.3.2.106, nvidia-cusolver-cu12==11.4.5.107, nvidia-cusparse-cu12==12.1.0.106, nvidia-nccl-cu12==2.19.3, nvidia-nvjitlink-cu12==12.3.101, nvidia-nvtx-cu12==12.1.105, oauthlib==3.2.2, odfpy==1.4.1, openTSNE==1.0.1, openpyxl==3.1.2, orange-canvas-core==0.1.35, orange-widget-base==4.22.0, owlready2==0.45, packaging==23.2, pandas==2.2.1, parso==0.8.3, pexpect==4.9.0, pillow==10.2.0, pip==22.0.4, platformdirs==4.2.0, plotly==5.19.0, preshed==3.0.9, prompt-toolkit==3.0.43, psutil==5.9.8, ptyprocess==0.7.0, pure-eval==0.2.2, pybind11==2.11.1, pycparser==2.21, pydantic-core==2.16.3, pydantic==2.6.3, pydot==2.0.0, pygments==2.17.2, pyparsing==3.1.1, pypdf==4.1.0, pyqtgraph==0.13.3, python-dateutil==2.9.0.post0, python-louvain==0.16, pytz==2024.1, pyzmq==25.1.2, qasync==0.27.1, qtconsole==5.5.1, rapidfuzz==3.6.1, recommonmark==0.7.1, regex==2023.12.25, requests-cache==1.2.0, requests-oauthlib==1.3.1, requests==2.31.0, safetensors==0.4.2, scikit-learn==1.3.2, scipy==1.12.0, segtok==1.5.11, serverfiles==0.3.1, setuptools==58.1.0, shapely==2.0.3, simhash==2.1.2, six==1.16.0, smart-open==6.4.0, sniffio==1.3.1, snowballstemmer==2.2.0, soupsieve==2.5, spacy-legacy==3.0.12, spacy-loggers==1.0.5, spacy==3.7.4, sphinx==7.2.6, sphinxcontrib-applehelp==1.0.8, sphinxcontrib-devhelp==1.0.6, sphinxcontrib-htmlhelp==2.0.5, sphinxcontrib-jsmath==1.0.1, sphinxcontrib-qthelp==1.0.7, sphinxcontrib-serializinghtml==1.1.10, srsly==2.4.8, stack-data==0.6.3, storynavigator==0.0.11, sympy==1.12, tabulate==0.9.0, tenacity==8.2.3, textblob-nl==0.0.1, textblob==0.18.0.post0, thefuzz==0.22.1, thinc==8.2.3, threadpoolctl==3.3.0, tokenizers==0.15.2, torch==2.2.1, tornado==6.4, tqdm==4.66.2, traitlets==5.14.1, transformers==4.38.2, trimesh==4.1.7, triton==2.2.0, tweepy==4.14.0, typer==0.9.0, typing-extensions==4.10.0, tzdata==2024.1, ufal.udpipe==1.3.1.1, url-normalize==1.4.3, urllib3==2.2.1, wasabi==1.1.2, wcwidth==0.2.13, weasel==0.3.4, wikipedia==1.4.0, xgboost==2.0.3, xlrd==2.0.1, yake==0.4.8, zipp==3.17.0
Machine ID:
aa7e8c73-d204-4802-a437-067c75a3dffd
Stack Trace:
Traceback (most recent call last):
  File "/home/flavio/repositories/projects/navigating-stories/orange-story-navigator/.venv/lib/python3.9/site-packages/Orange/widgets/utils/concurrent.py", line 591, in _on_task_done
    super()._on_task_done(future)
  File "/home/flavio/repositories/projects/navigating-stories/orange-story-navigator/.venv/lib/python3.9/site-packages/Orange/widgets/utils/concurrent.py", line 547, in _on_task_done
    self.on_exception(ex)
  File "/home/flavio/repositories/projects/navigating-stories/orange-story-navigator/orangecontrib/storynavigation/widgets/OWSNActorAnalysis.py", line 937, in on_exception
    raise ex
  File "/home/flavio/.pyenv/versions/3.9.13/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/flavio/repositories/projects/navigating-stories/orange-story-navigator/orangecontrib/storynavigation/widgets/OWSNActorAnalysis.py", line 612, in run
    self.valid_stories.append(self.stories[int(storyid)])
  File "/home/flavio/repositories/projects/navigating-stories/orange-story-navigator/.venv/lib/python3.9/site-packages/orangecontrib/text/corpus.py", line 549, in __getitem__
    c = super().__getitem__(key)
  File "/home/flavio/repositories/projects/navigating-stories/orange-story-navigator/.venv/lib/python3.9/site-packages/Orange/data/table.py", line 1168, in __getitem__
    return RowInstance(self, key)
  File "/home/flavio/repositories/projects/navigating-stories/orange-story-navigator/.venv/lib/python3.9/site-packages/Orange/data/table.py", line 96, in __init__
    self.id = table.ids[row_index]
IndexError: index 38 is out of bounds for axis 0 with size 38


```

##### Steps to reproduce the behavior
following widgets:
- widget `import documents`: subset of corona stories
- widget `file`: `dutch_halliday_action_list.csv`. set all columns to text.
- widget `elements`, fed from `import documents` and `file`. extract story elements with language `nl`, custom tags `process`, number of segments per story: `10`.
- connect `elements` to `data table` widget
- connect `data table` to `actors` widget

##### Additional info (worksheets, data, screenshots, ...)
![image](https://github.com/navigating-stories/orange-story-navigator/assets/55716026/0eac8a04-b120-4c86-94e4-d3c28afc9c67)

**Comment by f-hafner** [comment]
I just tried to run it again and it worked this time...

**Comment by f-hafner** [comment]
So it seems to be a problem when changing the number of segments per story and then rerunning the workflow

**Comment by f-hafner** [comment]
And I get the same error when changing the language in the `setting` widget from nl to en and re-running the workflow.

![image](https://github.com/navigating-stories/orange-story-navigator/assets/55716026/f3ef057b-9d64-4e7c-8b63-7ef391004983)

**Comment by kodymoodley** [comment]
@f-hafner can you help me reproduce this error? I cannot seem to on my installation.

**Comment by f-hafner** [comment]
It's really specific to the dataset, and a little unpredictable. I can share with you input data and workflow to reproduce. 

It's also doing something else I had not noticed: for some stories, the wrong text is shown in the actors widget -- ie, the text of Story A in the raw data is shown for story B (and for story B, it shows text of story C). But then, when I use the regexp filter, it shows the text from the right story

This is all using the same workflow as shown above.

**Comment by kodymoodley** [comment]
Confirmed will be fixed when #44 is fixed. I tested when re-running workflow (refreshing). Duplicate stories get added to the document window and these do not have corresponding story ids that have entries in the id - story dictionary.

**Comment by ThijsVroegh** [comment]
#44 is fixed and indeed as @kodymoodley  mentioned in the last comment, i could not reproduce the above-mentioned errors anymore. #37 will therefore be closed together with #44

**Comment by eriktks** [comment]
See PR #71
